version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sommoim-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sommoim
      POSTGRES_PASSWORD: sommoim123
      POSTGRES_DB: sommoim
    ports:
      - '5434:5432'
    volumes:
      - sommoim_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sommoim']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: sommoim-redis
    restart: unless-stopped
    ports:
      - '6381:6379'
    volumes:
      - sommoim_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sommoim_postgres_data:
    driver: local
  sommoim_redis_data:
    driver: local

networks:
  default:
    name: sommoim-network
